<a href="https://colab.research.google.com/github/sk-imran-dev/CodeOrbit-Tech-Task1/blob/main/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Friend_Task1_Raw_Sales_Dataset.xlsx to Friend_Task1_Raw_Sales_Dataset.xlsx

In [ ]:
import pandas as pd

df = pd.read_excel("Friend_Task1_Raw_Sales_Dataset.xlsx")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [ ]:
print("===== DATASET SHAPE =====")
print("Rows and Columns:", df.shape)

print("\n===== COLUMN NAMES =====")
print(df.columns.tolist())

print("\n===== FIRST 5 ROWS =====")
display(df.head())

print("\n===== LAST 5 ROWS =====")
display(df.tail())

print("\n===== DATASET INFORMATION =====")
df.info()

===== DATASET SHAPE =====
Rows and Columns: (503, 10)

===== COLUMN NAMES =====
['Order_ID', 'Customer_Name', 'City', 'Category', 'Product', 'Order_Date', 'Quantity', 'Sales_Amount', 'Payment_Method', 'Order_Status']

===== FIRST 5 ROWS =====

,Order_ID,Customer_Name,City,Category,Product,Order_Date,Quantity,Sales_Amount,Payment_Method,Order_Status
0,ORD0001,Rahul,Visakhapatnam,Stationery,Cooking Oil,2025-11-28,2,22126.17,Net Banking,Shipped
1,ORD0002,Kavya,Warangal,Stationery,Rice Bag,2025-10-28,8,6150.37,Net Banking,Completed
2,ORD0003,Rahul,Bangalore,Electronics,Rice Bag,2025-01-06,8,17048.85,UPI,Shipped
3,ORD0004,Sneha,Visakhapatnam,Clothing,Jeans,2025-09-20,2,18133.18,Cash,Cancelled
4,ORD0005,Sneha,Nellore,Furniture,Notebook,2025-06-08,1,21225.30,Credit Card,Cancelled

===== LAST 5 ROWS =====

,Order_ID,Customer_Name,City,Category,Product,Order_Date,Quantity,Sales_Amount,Payment_Method,Order_Status
498,ORD0499,Arjun,Kakinada,Furniture,Headphones,2025-05-09,4,20697.83,UPI,Completed
499,ORD0500,Neha,Bangalore,Groceries,Jeans,2025-12-01,9,6460.37,Credit Card,Completed
500,ORD0031,Arjun,Kakinada,Stationery,Cooking Oil,2025-04-21,2,15595.45,Credit Card,Pending
501,ORD0061,Arjun,Nellore,Groceries,T-Shirt,2025-04-01,4,20198.17,UPI,Cancelled
502,ORD0091,Rahul,Hyderabad,Furniture,Laptop,2025-04-07,7,956.45,UPI,Cancelled

===== DATASET INFORMATION =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        503 non-null    object
 1   Customer_Name   502 non-null    object
 2   City            502 non-null    object
 3   Category        503 non-null    object
 4   Product         502 non-null    object
 5   Order_Date      503 non-null    datetime64[ns]
 6   Quantity        503 non-null    int64
 7   Sales_Amount    498 non-null    float64
 8   Payment_Method  503 non-null    object
 9   Order_Status    503 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 39.4+ KB

In [ ]:
print("===== MISSING VALUES =====")
print(df.isnull().sum())

print("\n===== DUPLICATE ROWS =====")
print("Number of duplicate rows:", df.duplicated().sum())

print("\n===== UNIQUE VALUES =====")

for column in df.columns:
    print(f"\n{column}:")
    print(df[column].dropna().unique()[:20])

===== MISSING VALUES =====
Order_ID          0
Customer_Name     1
City              1
Category          0
Product           1
Order_Date        0
Quantity          0
Sales_Amount      5
Payment_Method    0
Order_Status      0
dtype: int64

===== DUPLICATE ROWS =====
Number of duplicate rows: 3

===== UNIQUE VALUES =====

Order_ID:
['ORD0001' 'ORD0002' 'ORD0003' 'ORD0004' 'ORD0005' 'ORD0006' 'ORD0007'
 'ORD0008' 'ORD0009' 'ORD0010' 'ORD0011' 'ORD0012' 'ORD0013' 'ORD0014'
 'ORD0015' 'ORD0016' 'ORD0017' 'ORD0018' 'ORD0019' 'ORD0020']

Customer_Name:
['Rahul' 'Kavya' 'Sneha' 'Vikram' 'Neha' 'Sandeep' 'Pooja' '  Ananya  '
 'Kiran' 'Ananya' 'Rohit' 'Swathi' 'Arjun' 'Divya' 'Manoj' 'Priya']

City:
['Visakhapatnam' 'Warangal' 'Bangalore' 'Nellore' 'Tirupati' 'Kakinada'
 'Guntur' 'Vijayawada' 'Hyderabad' ' Vijayawada ' 'Chennai' 'guntur']

Category:
['Stationery' 'Electronics' 'Clothing' 'Furniture' 'Groceries'
 'electronics' 'FURNITURE']

Product:
['Cooking Oil' 'Rice Bag' 'Jeans' 'Notebook' 'Table' 'Office Chair'
 'T-Shirt' 'Laptop' 'Smartphone' 'Headphones' ' Laptop ']

Order_Date:
<DatetimeArray>
['2025-11-28 00:00:00', '2025-10-28 00:00:00', '2025-01-06 00:00:00',
 '2025-09-20 00:00:00', '2025-06-08 00:00:00', '2025-10-27 00:00:00',
 '2025-09-26 00:00:00', '2025-04-25 00:00:00', '2025-03-14 00:00:00',
 '2025-10-14 00:00:00', '2025-05-31 00:00:00', '2025-04-13 00:00:00',
 '2025-05-29 00:00:00', '2025-04-04 00:00:00', '2025-02-19 00:00:00',
 '2025-08-20 00:00:00', '2025-10-07 00:00:00', '2025-09-09 00:00:00',
 '2025-08-02 00:00:00', '2025-09-24 00:00:00']
Length: 20, dtype: datetime64[ns]

Quantity:
[ 2  8  1  9  5  3  7  6  4 10]

Sales_Amount:
[22126.17  6150.37 17048.85 18133.18 21225.3  12561.69 21143.05 20489.68
 22130.79 16809.9    430.07 17377.67 11549.86 21092.51 18739.27 13755.45
 16778.23 13735.93 23389.39  9524.95]

Payment_Method:
['Net Banking' 'UPI' 'Cash' 'Credit Card' 'Debit Card' ' UPI '
 'credit card']

Order_Status:
['Shipped' 'Completed' 'Cancelled' 'Pending']

In [ ]:
print("===== DATA TYPES =====")
print(df.dtypes)

print("\n===== QUANTITY VALUES =====")
print(df["Quantity"].unique())

print("\n===== SALES AMOUNT SAMPLE =====")
print(df["Sales_Amount"].head(20))

print("\n===== ORDER DATE SAMPLE =====")
print(df["Order_Date"].head(10))

===== DATA TYPES =====
Order_ID                  object
Customer_Name             object
City                      object
Category                  object
Product                   object
Order_Date        datetime64[ns]
Quantity                   int64
Sales_Amount             float64
Payment_Method            object
Order_Status              object
dtype: object

===== QUANTITY VALUES =====
[ 2  8  1  9  5  3  7  6  4 10]

===== SALES AMOUNT SAMPLE =====
0     22126.17
1      6150.37
2     17048.85
3     18133.18
4     21225.30
5     12561.69
6     21143.05
7     20489.68
8     22130.79
9     16809.90
10      430.07
11    17377.67
12    11549.86
13    21092.51
14    18739.27
15    13755.45
16    16778.23
17    13735.93
18    23389.39
19     9524.95
Name: Sales_Amount, dtype: float64

===== ORDER DATE SAMPLE =====
0   2025-11-28
1   2025-10-28
2   2025-01-06
3   2025-09-20
4   2025-06-08
5   2025-10-27
6   2025-09-26
7   2025-04-25
8   2025-03-14
9   2025-10-14
Name: Order_Date, dtype: datetime64[ns]

In [ ]:
# Remove duplicate rows
df = df.drop_duplicates()

# Identify text columns
text_columns = df.select_dtypes(include="object").columns

# Remove extra spaces
for column in text_columns:
    df[column] = df[column].str.strip()

# Standardize text capitalization
for column in text_columns:
    df[column] = df[column].str.title()

# Convert Quantity to numeric
df["Quantity"] = pd.to_numeric(
    df["Quantity"],
    errors="coerce"
)

# Convert Sales Amount to numeric
df["Sales_Amount"] = pd.to_numeric(
    df["Sales_Amount"],
    errors="coerce"
)

# Convert Order Date to datetime
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    errors="coerce"
)

# Handle missing text values
df["Customer_Name"] = df["Customer_Name"].fillna("Unknown")
df["City"] = df["City"].fillna("Unknown")
df["Category"] = df["Category"].fillna("Unknown")
df["Product"] = df["Product"].fillna("Unknown")
df["Payment_Method"] = df["Payment_Method"].fillna("Unknown")
df["Order_Status"] = df["Order_Status"].fillna("Unknown")

print("Data cleaning completed!")

display(df.head())

Data cleaning completed!

,Order_ID,Customer_Name,City,Category,Product,Order_Date,Quantity,Sales_Amount,Payment_Method,Order_Status
0,Ord0001,Rahul,Visakhapatnam,Stationery,Cooking Oil,2025-11-28,2,22126.17,Net Banking,Shipped
1,Ord0002,Kavya,Warangal,Stationery,Rice Bag,2025-10-28,8,6150.37,Net Banking,Completed
2,Ord0003,Rahul,Bangalore,Electronics,Rice Bag,2025-01-06,8,17048.85,Upi,Shipped
3,Ord0004,Sneha,Visakhapatnam,Clothing,Jeans,2025-09-20,2,18133.18,Cash,Cancelled
4,Ord0005,Sneha,Nellore,Furniture,Notebook,2025-06-08,1,21225.30,Credit Card,Cancelled

In [ ]:
# Calculate median Sales Amount
median_sales = df["Sales_Amount"].median()

print("Median Sales Amount:", median_sales)

# Replace missing Sales Amount values
df["Sales_Amount"] = df["Sales_Amount"].fillna(median_sales)

print(
    "\nMissing Sales Amounts after cleaning:",
    df["Sales_Amount"].isnull().sum()
)

Median Sales Amount: 12902.61

Missing Sales Amounts after cleaning: 0

In [ ]:
print("===== FINAL DATASET CHECK =====")

print("\nDataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

print("\nFirst 5 Cleaned Records:")
display(df.head())

print("\nLast 5 Cleaned Records:")
display(df.tail())

===== FINAL DATASET CHECK =====

Dataset Shape:
(500, 10)

Missing Values:
Order_ID          0
Customer_Name     0
City              0
Category          0
Product           0
Order_Date        0
Quantity          0
Sales_Amount      0
Payment_Method    0
Order_Status      0
dtype: int64

Duplicate Rows:
0

Data Types:
Order_ID                  object
Customer_Name             object
City                      object
Category                  object
Product                   object
Order_Date        datetime64[ns]
Quantity                   int64
Sales_Amount             float64
Payment_Method            object
Order_Status              object
dtype: object

First 5 Cleaned Records:

,Order_ID,Customer_Name,City,Category,Product,Order_Date,Quantity,Sales_Amount,Payment_Method,Order_Status
0,Ord0001,Rahul,Visakhapatnam,Stationery,Cooking Oil,2025-11-28,2,22126.17,Net Banking,Shipped
1,Ord0002,Kavya,Warangal,Stationery,Rice Bag,2025-10-28,8,6150.37,Net Banking,Completed
2,Ord0003,Rahul,Bangalore,Electronics,Rice Bag,2025-01-06,8,17048.85,Upi,Shipped
3,Ord0004,Sneha,Visakhapatnam,Clothing,Jeans,2025-09-20,2,18133.18,Cash,Cancelled
4,Ord0005,Sneha,Nellore,Furniture,Notebook,2025-06-08,1,21225.30,Credit Card,Cancelled

Last 5 Cleaned Records:

,Order_ID,Customer_Name,City,Category,Product,Order_Date,Quantity,Sales_Amount,Payment_Method,Order_Status
495,Ord0496,Swathi,Kakinada,Stationery,Cooking Oil,2025-10-23,6,2358.97,Net Banking,Pending
496,Ord0497,Neha,Chennai,Furniture,T-Shirt,2025-10-20,5,21592.13,Net Banking,Pending
497,Ord0498,Pooja,Visakhapatnam,Clothing,Notebook,2025-02-28,5,10424.63,Credit Card,Pending
498,Ord0499,Arjun,Kakinada,Furniture,Headphones,2025-05-09,4,20697.83,Upi,Completed
499,Ord0500,Neha,Bangalore,Groceries,Jeans,2025-12-01,9,6460.37,Credit Card,Completed

In [ ]:
cleaned_file = "Friend_Task1_Cleaned_Sales_Dataset.csv"

df.to_csv(cleaned_file, index=False)

print("Cleaned dataset saved successfully!")
print("File name:", cleaned_file)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Cleaned dataset saved successfully!
File name: Friend_Task1_Cleaned_Sales_Dataset.csv
Rows: 500
Columns: 10

In [ ]:
from google.colab import files

files.download("Friend_Task1_Cleaned_Sales_Dataset.csv")